### PR TITLE
Adding humble/garden support

### PR DESCRIPTION
**Pull request by bsb808**
This PR adds a Dockerfile for Humble (Ubuntu 22.04 Jammy Jellyfish / ROS 2 Humble Hawksbill / Gazebo Garden).

Test using VRX by...

1. Build the dockwater image in the usual way.
2. Build VRX - https://github.com/osrf/vrx/wiki/2023-installation
3. And run the VRX demo - https://github.com/osrf/vrx/wiki/2023-running_vrx

### CODE REVIEW

**Comment by bsb808** [comment]
@M1chaelM - Now that we have galactic working, could you review this humble setup for VRX?

**Comment by M1chaelM** [comment]
Running
```
./build.bash humble
```
gave me the following error:
```
W: http://packages.ros.org/ros2/ubuntu/dists/jammy/InRelease: Key is stored in legacy trusted.gpg keyring (/etc/apt/trusted.gpg), see the DEPRECATION section in apt-key(8) for details.
E: Problem executing scripts APT::Update::Post-Invoke 'rm -f /var/cache/apt/archives/*.deb /var/cache/apt/archives/partial/*.deb /var/cache/apt/*.bin || true'
E: Sub-process returned an error code
```

**Comment by M1chaelM** [comment]
Digging further, running
```
docker run -it ros:humble-ros-base-jammy /bin/bash
```
produces a prompt into the base image. Then
```
apt update
```
reproduces the error. So it looks like there is a problem with the upstream image. I pursued this further and I get this `Problem executing scripts` error all the way up to the `ubuntu:jammy` base image. This is surprising, so maybe I have somehow produced a conflict on my local system. I don't see this problem with other ubuntu images, like `ubuntu:focal`

Update: This may be a surprising consequence of a conflict with my Docker version and upgraded host OS: https://stackoverflow.com/questions/71941032/why-i-cannot-run-apt-update-inside-a-fresh-ubuntu22-04

**Comment by bsb808** [comment]
Hmm - I'll check my setup (Host OS and docker version details) from work with the working setup.  What is your configuration?

So much for docker making things platform independent ;)

**Comment by M1chaelM** [comment]
I think the problem is that I upgraded the host to Jammy, and you probably did not. The Docker bug only affects people running on Jammy, and you have to do a little work to upgrade to a newer version of Docker because the default package you get through apt is a few minor versions back and still has the bug in it.

Docker is now updated and the image is building as expected...

**Comment by M1chaelM** [comment]
I can now run the simulation but the joystick teleop is not working. Might be missing a package:
```
ros2 launch vrx_gz usv_joy_teleop.py
[INFO] [launch]: All log files can be found below /home/user/.ros/log/2022-10-12-22-59-34-537846-a241b35a8ab4-66054
[INFO] [launch]: Default logging verbosity is set to INFO
[ERROR] [launch]: Caught exception in launch (see debug for traceback): "package 'joy_teleop' not found, searching: ['/home/user/dock_ws/install', '/opt/ros/humble']"
```

**Review by M1chaelM — APPROVED** [review]
I think this is working correctly in that the latest version of VRX will build and run on it. There seems to be a problem with gamepad support when the local host is Ubuntu 22. However, if I install jstest-gtk I can see the system is responding to the controller, so I think the problem is probably with VRX rather than the image.

It would be good to know whether the usv_joy_teleop.py is working as expected when the local host is on Ubuntu 20 or 18.

**Comment by j-herman** [comment]
@M1chaelM @bsb808 I tried to build the humble container from this branch and ran into an error with python3-sdformat13:

> E: Unable to locate package python3-sdformat13

I got the same error trying to install the package in a basic docker container.  To fix this, I relocated the install command:
`apt install ...
python3-sdformat13 \`
from the first section of installs to the last section, where we install python3-colcon-common-extensions.
With this change, the container builds.  I'm having driver problems and it does *not* currently run but that is probably due to rocker/ nvidia compatibility.  
Before merging this branch, recommend rechecking with a clean build to see if this is just a quirk on my system or if we need to make the change.  I did this check on my desktop running 22.04 and with humble/ garden already installed.
It's possible that sdformat13 ships with gazebo, but the messages went by so fast that I couldn't verify the "is already the latest version" was attached to this package.

**Comment by M1chaelM** [comment]
> I got the same error trying to install the package in a basic docker container. To fix this, I relocated the install command:
> `apt install ... python3-sdformat13 \`

This change seems fine to me, but I'm not sure I understand the reasoning behind it. I have re-run a fresh install and it is working so I am going to merge. I think we'll have the opportunity to test further and fix bugs if we find them once other users start using this for VRX.

**Pull request merged**
