### PR TITLE
Build, run and join default arguments.

### PR DESCRIPTION
**Pull request by bsb808**
Adds a default=noetic for the build, run and join scripts b/c I always forget the tag names ;)

### CODE REVIEW

**Review by M1chaelM — COMMENTED** [review]
I'm hesitant to make this change for the following reasons:
* The build image name is always the same as a subdirectory in the repo, so you can find it with `ls`.
* The build script already outputs the command you need for the `run` script.
* If you forget the container ID you can find it with `docker container ls`

Instead, could we add a line to the build script that also echos the join command?

**Comment by bsb808** [comment]
I can get behind 1 and 3, but when you build once, and then days later want to run the image, it is hard to remember the name - I find I always have to go to the wiki.  IMHO opinion defaults are nice and you can always add the argument.

I guess the question is why not add defaults?

**Comment by M1chaelM** [comment]
> I guess the question is why not add defaults?

I'm not absolutely opposed, but to answer your question I have two reasons:
1. I'm wary of how quickly our bash scripts accumulate complexity. So with each addition I'm eyeing the tradeoff between the additional complexity and the functionality we get for it.
2. I agree that it's good to have sensible defaults but in this case I think we have that already. The default if you don't specify an image you want to use is just not to run it (as opposed to crashing or doing something unexpected). Arguably, a default that assumes you have built an image that you might not have built could end up being more confusing, in my opinion.

In this case, I admit it's not a ton of added complexity (though I would prefer to avoid reading input from the command line if we don't have to), but if the problem is just remembering the name of the image it seems like a better solution is to run:
```
docker image ls
```
to see what you built. Could be that I'm too far into this, so I don't mean to be difficult, but just wanted to see whether that command would resolve the issue for you.

**Comment by M1chaelM** [comment]
@bsb808 What do you think of this as an alternative: #8 ?

**Comment by bsb808** [comment]
closed by addressed elsewhere.

**Pull request closed without merging**
